"""
Zone music: one ~60 second, seamlessly looping, ORIGINAL 8-bit rock track per
zone (Nexus, Bazaar, Vault, the 10 Realm biomes, the 2 island themes and every
dungeon theme incl. the Forge).

Every song is composed procedurally from a small data spec (key, scale,
tempo, groove style, chord progressions per section and a melody seed) - the
melodies are generated by a seeded random walk over the scale with
chord-tone targeting, so nothing here reproduces any existing song. The same
toolkit the old themes used (square/pulse lead, root+fifth power chords,
triangle bass, noise kick/snare/hi-hat) - just rendered much faster:

* each note is a repeated single-cycle wavetable (bytes * n, C speed) with a
  segment-wise envelope applied through audioop.mul, and every note/drum is
  mixed into the song buffer with audioop.add (saturating, C speed) - a full
  minute renders in well under a second instead of the old per-sample Python
  loops;
* songs are rendered CIRCULARLY: the ringing tail of the last bar is folded
  back onto the first samples, so the loop point is a perfectly continuous,
  bar-aligned seam (no click, no gap);
* rendered tracks are cached to disk as .wav (music_cache/, keyed by a hash of
  this file + the spec + the sample rate, so editing a song invalidates only
  that cache entry) and rendered on a background worker thread - the game
  loop never waits for music (see request()).

RR_NO_MUSIC=1 (set by tests/run_all_checks.py) turns the background worker
and playback off; render() itself still works for tests.
"""
import hashlib
import io
import math
import os
import random
import threading
import wave
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore", DeprecationWarning)
    try:
        import audioop  # deprecated (removed in 3.13) but present on the project's 3.12
    except ImportError:  # pragma: no cover - pure-Python fallback below
        audioop = None

RATE = 22050        # mono 16-bit; pygame resamples to the mixer's own rate on load
TARGET_SECONDS = 60.0
TAIL_SECONDS = 2.5  # ringing notes past the last bar, folded back onto the start

SCALES = {
    "major": (0, 2, 4, 5, 7, 9, 11), "aeolian": (0, 2, 3, 5, 7, 8, 10),
    "dorian": (0, 2, 3, 5, 7, 9, 10), "phrygian": (0, 1, 3, 5, 7, 8, 10),
    "mixolydian": (0, 2, 4, 5, 7, 9, 10), "harmonic_minor": (0, 2, 3, 5, 7, 8, 11),
    "phrygian_dominant": (0, 1, 4, 5, 7, 8, 10), "lydian": (0, 2, 4, 6, 7, 9, 11),
}


def _spec(title, key, scale, bpm, style, seed, verse, chorus, bridge, lead="square", desc=""):
    return dict(title=title, key=key, scale=scale, bpm=bpm, style=style, seed=seed,
                prog={"intro": verse, "verse": verse, "chorus": chorus, "bridge": bridge},
                lead=lead, desc=desc)


# key = MIDI note of the bass root (40 = E2). Chord progressions are scale degrees
# (0-based), one chord per bar. Every entry is its own original composition.
TRACKS = {
    # --- hubs
    "nexus": _spec("Hearthlight", 38, "mixolydian", 92, "ballad", 11, [0, 4, 6, 3], [3, 0, 4, 6], [5, 3], "pulse",
                   "soft-rock ballad, arpeggiated chords, warm pulse lead in D mixolydian"),
    "bazaar": _spec("Haggle Boogie", 45, "mixolydian", 150, "shuffle", 23, [0, 3, 0, 4], [3, 3, 0, 4], [5, 4],
                    "square", "swung rock'n'roll shuffle with walking bass in A"),
    "vault": _spec("Counting Room", 37, "dorian", 84, "halftime", 37, [0, 6, 5, 4], [3, 4, 0, 0], [2, 3],
                   "triangle", "moody half-time groove, sustained chords, low triangle lead in C# dorian"),
    # --- realm biomes
    "forest": _spec("Greenwood Charge", 40, "aeolian", 124, "rock", 101, [0, 5, 6, 0], [5, 6, 0, 0], [3, 4],
                    "square", "heroic mid-tempo rock anthem in E minor"),
    "desert": _spec("Mirage Road", 40, "phrygian_dominant", 112, "rock", 113, [0, 1, 0, 6], [1, 0, 6, 0], [3, 1],
                    "pulse", "dusty desert rock on an E phrygian-dominant riff"),
    "tundra": _spec("Whiteout", 35, "aeolian", 100, "halftime", 127, [0, 3, 5, 6], [5, 3, 0, 6], [2, 5],
                    "triangle", "icy wide post-rock, half-time drums, B minor"),
    "swamp": _spec("Bog Blues", 43, "dorian", 88, "shuffle", 131, [0, 0, 3, 0], [3, 3, 0, 4], [4, 3],
                   "square", "sludgy swamp blues shuffle in G"),
    "highlands": _spec("Windcrest Gallop", 38, "dorian", 140, "gallop", 149, [0, 6, 5, 6], [2, 6, 0, 4], [3, 5],
                       "square", "galloping power-metal anthem in D dorian"),
    "ashlands": _spec("Cinder Sprint", 40, "phrygian", 168, "punk", 157, [0, 1, 0, 6], [5, 6, 1, 0], [3, 1],
                      "pulse", "fast thrash-punk in E phrygian with driving eighths"),
    "jungle": _spec("Canopy Drums", 42, "dorian", 118, "tribal", 163, [0, 3, 0, 6], [3, 4, 6, 0], [2, 3],
                    "pulse", "tribal-tom rock groove in F# dorian"),
    "wasteland": _spec("Rust Belt", 45, "aeolian", 96, "halftime", 173, [0, 5, 3, 4], [5, 3, 6, 4], [1, 4],
                       "square", "grungy half-time sludge in A minor"),
    "ice": _spec("Glass Cathedral", 37, "harmonic_minor", 132, "rock", 181, [0, 5, 3, 4], [5, 4, 0, 4], [3, 6],
                 "triangle", "crystalline arpeggio rock in C# harmonic minor"),
    "cave": _spec("Deep Echo", 38, "phrygian", 76, "doom", 191, [0, 1, 0, 6], [1, 6, 5, 0], [3, 1],
                  "triangle", "slow doom crawl in D phrygian"),
    # --- islands (one per island theme)
    "island_shard": _spec("Shard Surf", 40, "major", 156, "surf", 211, [0, 3, 4, 3], [5, 3, 0, 4], [1, 4],
                          "pulse", "sunny tremolo surf-rock in E major"),
    "island_choir": _spec("Choir Tide", 43, "mixolydian", 104, "offbeat", 223, [0, 6, 3, 0], [3, 4, 0, 6], [5, 4],
                          "square", "laid-back off-beat island rock in G"),
    # --- dungeons
    "dungeon": _spec("Forgotten Halls", 38, "aeolian", 108, "rock", 307, [0, 6, 5, 4], [5, 6, 0, 0], [3, 4],
                     "square", "classic dungeon-crawl rock in D minor"),
    "dungeon_cave": _spec("Warren Crawl", 36, "phrygian", 84, "doom", 311, [0, 1, 6, 0], [1, 0, 6, 5], [3, 1],
                          "triangle", "creeping doom with low triangle lead in C"),
    "dungeon_frozen_crypt": _spec("Crypt Frost", 39, "harmonic_minor", 96, "halftime", 313, [0, 5, 4, 0],
                                  [5, 3, 4, 4], [1, 4], "triangle", "cold gothic half-time in D# harmonic minor"),
    "dungeon_jungle_ruins": _spec("Idol Run", 42, "phrygian_dominant", 126, "tribal", 317, [0, 1, 0, 4],
                                  [1, 0, 6, 0], [3, 4], "pulse", "ruin-raider tribal rock in F#"),
    "dungeon_ember_den": _spec("Magma Stomp", 40, "phrygian", 150, "gallop", 331, [0, 1, 6, 1], [5, 6, 0, 1],
                               [3, 1], "square", "molten galloping metal in E phrygian"),
    "dungeon_sunken_grotto": _spec("Drowned Bells", 41, "dorian", 98, "offbeat", 337, [0, 3, 6, 3], [5, 3, 0, 4],
                                   [1, 3], "triangle", "watery off-beat groove in F dorian"),
    "dungeon_wind_spire": _spec("Updraft", 43, "lydian", 136, "surf", 347, [0, 1, 4, 1], [3, 1, 0, 4], [5, 1],
                                "pulse", "soaring lydian tremolo rock in G"),
    "dungeon_forge": _spec("Closing Time", 40, "harmonic_minor", 176, "punk", 353, [0, 5, 4, 0], [5, 3, 4, 4],
                           [1, 4], "square", "frantic finale speed-rock in E harmonic minor"),
}

# the dungeon label a co-op client receives over the network -> track key
DUNGEON_LABEL_TO_KEY = {
    "Cave Warren": "cave", "Frozen Crypt": "frozen_crypt", "Jungle Ruins": "jungle_ruins",
    "Ember Den": "ember_den", "Sunken Grotto": "sunken_grotto", "Wind Spire": "wind_spire",
    "Forgotten Vault": "generic", "The Forge": "forge",
}
BIOMES = ("forest", "desert", "tundra", "swamp", "highlands", "ashlands", "jungle", "wasteland", "ice", "cave")


def dungeon_zone_for_key(theme_key):
    zone = f"dungeon_{theme_key}"
    return zone if zone in TRACKS else "dungeon"


def dungeon_zone_for_label(label):
    return dungeon_zone_for_key(DUNGEON_LABEL_TO_KEY.get(label))


def realm_zone(biome_name=None, island_idx=None):
    """The track for a spot in the open Realm: its island's theme if on an island
    (themes alternate shard/choir by island index), else its biome."""
    if island_idx is not None:
        return "island_shard" if island_idx % 2 == 0 else "island_choir"
    return biome_name if biome_name in TRACKS else "forest"


# ----------------------------------------------------------------- timing

def bars_for(bpm):
    """Bar count (even, so sections pair up) giving a length closest to 60s."""
    return max(4, 2 * round(bpm * TARGET_SECONDS / 480.0))


def length_seconds(spec):
    return bars_for(spec["bpm"]) * 4 * 60.0 / spec["bpm"]


def plan_sections(bars):
    """[(section, n_bars)] exactly filling `bars` - intro, then verse/chorus/
    bridge development, never the same 8 bars twice in a row."""
    template = [("intro", 4), ("verse", 8), ("chorus", 8), ("bridge", 4), ("chorus", 8), ("verse", 8),
                ("chorus", 8), ("bridge", 4), ("chorus", 8), ("chorus", 8)]
    out, used = [], 0
    for name, n in template:
        if used >= bars:
            break
        n = min(n, bars - used)
        out.append((name, n))
        used += n
    while used < bars:
        n = min(8, bars - used)
        out.append(("chorus", n))
        used += n
    return out


# ------------------------------------------------------------- synthesis

_TABLES = {}
_NOISE = None
_DRUMS = {}


def _cycle(wave_kind, period):
    key = (wave_kind, period)
    if key in _TABLES:
        return _TABLES[key]
    a = 30000
    vals = []
    for i in range(period):
        ph = i / period
        if wave_kind == "square":
            v = a if ph < 0.5 else -a
        elif wave_kind == "pulse":      # 25% duty - the thinner NES lead voice
            v = a if ph < 0.25 else -a
        elif wave_kind == "triangle":
            v = int(a * (4 * ph - 1 if ph < 0.5 else 3 - 4 * ph))
        elif wave_kind == "saw":
            v = int(a * (2 * ph - 1))
        else:                           # sine
            v = int(a * math.sin(2 * math.pi * ph))
        vals.append(v)
    b = _pack(vals)
    _TABLES[key] = b
    return b


def _pack(vals):
    import array
    arr = array.array("h", (max(-32767, min(32767, int(v))) for v in vals))
    return arr.tobytes()


def _mul(frag, factor):
    if audioop is not None:
        return audioop.mul(frag, 2, factor)
    import array
    arr = array.array("h")
    arr.frombytes(frag)
    return _pack(v * factor for v in arr)


def _add(a, b):
    if audioop is not None:
        return audioop.add(a, b, 2)
    import array
    x, y = array.array("h"), array.array("h")
    x.frombytes(a)
    y.frombytes(b)
    return _pack(p + q for p, q in zip(x, y))


def _envelope(raw, vol, attack=0.004, release=0.03, decay=None, seg=96):
    """Segment-wise envelope (C-speed audioop.mul per ~4ms segment): linear attack,
    optional exponential decay, linear release to exactly 0 at the note end."""
    n = len(raw) // 2
    if n == 0:
        return raw
    att, rel = max(1, int(attack * RATE)), max(1, int(release * RATE))
    parts = []
    for s0 in range(0, n, seg):
        s1 = min(n, s0 + seg)
        mid = (s0 + s1) / 2
        g = 1.0
        if mid < att:
            g = mid / att
        if decay is not None:
            g *= math.exp(-decay * mid / RATE)
        if mid > n - rel:
            g *= max(0.0, (n - mid) / rel)
        if s1 >= n:
            g = 0.0 if n - s0 <= seg else g
        parts.append(_mul(raw[s0 * 2:s1 * 2], vol * g))
    return b"".join(parts)


_NOTE_CACHE = {}


def _tone(freq, dur, vol, wave_kind="square", attack=0.004, release=0.03, decay=None):
    key = (round(freq, 2), round(dur, 4), round(vol, 3), wave_kind, attack, release, decay)
    hit = _NOTE_CACHE.get(key)
    if hit is not None:
        return hit
    n = max(2, int(dur * RATE))
    period = max(2, int(round(RATE / max(20.0, freq))))
    cyc = _cycle(wave_kind, period)
    raw = (cyc * (n // period + 1))[:n * 2]
    out = _envelope(raw, vol, attack, release, decay)
    _NOTE_CACHE[key] = out
    return out


def _noise(n):
    global _NOISE
    if _NOISE is None or len(_NOISE) < n * 2:
        rng = random.Random(4242)
        _NOISE = _pack(rng.randint(-30000, 30000) for _ in range(max(n, RATE)))
    return _NOISE[:n * 2]


def _sweep(f0, f1, dur, vol, decay):
    n = int(dur * RATE)
    vals, ph = [], 0.0
    for i in range(n):
        f = f0 + (f1 - f0) * (i / n)
        ph += f / RATE
        vals.append(30000 * math.sin(2 * math.pi * ph) * vol * math.exp(-decay * i / RATE))
    return _pack(vals)


def _drum(kind):
    if kind in _DRUMS:
        return _DRUMS[kind]
    if kind == "kick":
        d = _sweep(120, 42, 0.18, 0.55, 14)
    elif kind == "snare":
        d = _add(_envelope(_noise(int(0.14 * RATE)), 0.30, decay=22, release=0.02),
                 _envelope(_tone(190, 0.14, 1.0, "triangle", release=0.02), 0.25, decay=30, release=0.02))
    elif kind == "hat":
        d = _envelope(_noise(int(0.035 * RATE)), 0.10, decay=90, release=0.01)
    elif kind == "crash":
        d = _envelope(_noise(int(1.1 * RATE)), 0.16, decay=3.5, release=0.2)
    elif kind == "tom_hi":
        d = _sweep(210, 140, 0.2, 0.45, 12)
    else:  # tom_lo
        d = _sweep(130, 85, 0.25, 0.5, 10)
    _DRUMS[kind] = d
    return d


def _freq(midi):
    return 440.0 * 2 ** ((midi - 69) / 12.0)


class _Buf:
    def __init__(self, n_samples):
        self.n = n_samples
        self.data = bytearray(n_samples * 2)

    def add(self, sample_pos, frag):
        a = sample_pos * 2
        if a >= len(self.data) or a < 0:
            return
        b = min(len(self.data), a + len(frag))
        seg = bytes(self.data[a:b])
        self.data[a:b] = _add(seg, frag[:b - a])


# ------------------------------------------------------------ composition

def _chord_root(spec, degree, octave=0):
    sc = SCALES[spec["scale"]]
    return spec["key"] + sc[degree % len(sc)] + 12 * (degree // len(sc) + octave)


def _scale_notes(spec, lo, hi):
    sc = SCALES[spec["scale"]]
    out = []
    for m in range(lo, hi + 1):
        if (m - spec["key"]) % 12 in sc:
            out.append(m)
    return out


_RHYTHMS = {  # per-bar lead rhythms in 16th steps (sum 16) - picked per section by seed
    "rock": [(4, 2, 2, 4, 4), (2, 2, 4, 2, 2, 4), (3, 3, 2, 4, 4), (4, 4, 2, 2, 4)],
    "gallop": [(3, 1, 4, 3, 1, 4), (2, 2, 2, 2, 4, 4), (4, 2, 2, 4, 4)],
    "punk": [(2, 2, 2, 2, 4, 4), (4, 4, 4, 4), (2, 2, 4, 4, 4)],
    "shuffle": [(3, 1, 3, 1, 4, 4), (4, 3, 1, 4, 4), (6, 2, 4, 4)],
    "ballad": [(8, 4, 4), (4, 4, 8), (6, 2, 8)],
    "halftime": [(8, 8), (6, 2, 8), (4, 4, 8)],
    "doom": [(16,), (8, 8), (12, 4)],
    "tribal": [(3, 3, 2, 4, 4), (2, 2, 4, 4, 4), (4, 2, 2, 8)],
    "surf": [(2, 2, 2, 2, 2, 2, 4), (4, 2, 2, 4, 4), (2, 2, 4, 2, 2, 4)],
    "offbeat": [(4, 4, 4, 4), (6, 2, 4, 4), (4, 2, 2, 8)],
}


def _melody(spec, rng, bars, prog, register, rhythm_bank):
    """A 2-bar motif + answer, developed over `bars` bars: a seeded random walk
    over the scale that lands on chord tones on strong beats and resolves to
    the chord root at phrase ends. Returns [(step_offset, n_steps, midi|None)]."""
    notes = _scale_notes(spec, register, register + 14)
    motif_r = [rng.choice(rhythm_bank) for _ in range(2)]
    motif_moves = [rng.choice((-2, -1, -1, 1, 1, 2, 3, -3, 0)) for _ in range(16)]
    out = []
    idx = rng.randrange(2, len(notes) - 4)
    for bar in range(bars):
        chord = prog[bar % len(prog)]
        root_pc = (_chord_root(spec, chord)) % 12
        chord_pcs = {root_pc, (root_pc + 7) % 12, (root_pc + 3) % 12, (root_pc + 4) % 12}
        rhythm = motif_r[bar % 2]
        if bar % 4 == 3:            # answer phrase: vary the rhythm, end long on the root
            rhythm = rhythm_bank[(bar // 4 + 1) % len(rhythm_bank)]
        step = 0
        for j, dur in enumerate(rhythm):
            move = motif_moves[(j + (bar % 2) * 5) % len(motif_moves)]
            if bar % 8 >= 4:
                move = -move if rng.random() < 0.5 else move   # development in the second half
            idx = max(0, min(len(notes) - 1, idx + move))
            m = notes[idx]
            strong = step in (0, 8)
            if strong and (m % 12) not in chord_pcs:
                # nudge to the nearest chord tone on strong beats
                for d in (1, -1, 2, -2):
                    k = idx + d
                    if 0 <= k < len(notes) and notes[k] % 12 in chord_pcs:
                        idx = k
                        m = notes[k]
                        break
            last = j == len(rhythm) - 1
            if last and bar % 4 == 3:
                cands = [k for k, v in enumerate(notes) if v % 12 == root_pc]
                if cands:
                    idx = min(cands, key=lambda k: abs(k - idx))
                    m = notes[idx]
            rest = (not strong) and rng.random() < 0.12
            out.append((bar * 16 + step, dur, None if rest else m))
            step += dur
    return out


def compose_and_render(spec, rate=None):
    """-> raw mono 16-bit PCM bytes of exactly bars*bar_len samples, seamless loop."""
    global RATE
    old_rate = RATE
    if rate is not None and rate != RATE:
        RATE = rate
        _NOTE_CACHE.clear()
        _TABLES.clear()
        _DRUMS.clear()
    try:
        return _render(spec)
    finally:
        if RATE != old_rate:
            RATE = old_rate
            _NOTE_CACHE.clear()
            _TABLES.clear()
            _DRUMS.clear()


def _render(spec):
    rng = random.Random(spec["seed"])
    bpm, style = spec["bpm"], spec["style"]
    bars = bars_for(bpm)
    step_s = 60.0 / bpm / 4                  # one 16th note
    step_n = RATE * step_s
    total = int(round(bars * 16 * step_n))
    tail = int(TAIL_SECONDS * RATE)
    buf = _Buf(total + tail)

    def at(step):
        return int(round(step * step_n))

    bank = _RHYTHMS[style]
    bar0 = 0
    for sec, nbars in plan_sections(bars):
        prog = spec["prog"][sec]
        loud = {"intro": 0.75, "verse": 0.9, "chorus": 1.0, "bridge": 0.7}[sec]
        # ---- rhythm guitar (power chords) + bass
        for b in range(nbars):
            gbar = bar0 + b
            deg = prog[b % len(prog)]
            root = _chord_root(spec, deg, octave=1)
            s0 = gbar * 16
            _rhythm_bar(buf, at, s0, style, sec, root, step_s, loud)
            _bass_bar(buf, at, s0, style, root - 12, spec, deg, step_s, loud)
            _drum_bar(buf, at, s0, style, sec, b, nbars, loud)
        # ---- lead
        if sec != "intro" or style in ("ballad", "surf"):
            register = spec["key"] + 24 + (5 if sec == "chorus" else 0) + (7 if sec == "bridge" else 0)
            mel_rng = random.Random(spec["seed"] * 31 + {"intro": 1, "verse": 2, "chorus": 3, "bridge": 4}[sec])
            lead_vol = {"intro": 0.10, "verse": 0.13, "chorus": 0.15, "bridge": 0.11}[sec]
            bank_here = bank if sec != "bridge" else [r for r in _RHYTHMS["halftime"]]
            for st, dur, m in _melody(spec, mel_rng, nbars, prog, register, bank_here):
                if m is None:
                    continue
                d = dur * step_s * (0.92 if style != "punk" else 0.8)
                buf.add(at(bar0 * 16 + st), _tone(_freq(m), d, lead_vol, spec["lead"], release=0.025))
                if sec == "chorus" and style in ("gallop", "punk", "rock", "surf"):
                    # a harmony line a third above in the chorus - bigger "lift"
                    buf.add(at(bar0 * 16 + st), _tone(_freq(m + 4 if (m - spec["key"]) % 12 in (0, 5, 7) else m + 3),
                                                      d, lead_vol * 0.45, "pulse", release=0.025))
        bar0 += nbars

    data = buf.data
    # fold the tail (notes ringing past the last bar) back onto the start: a
    # circular render makes the loop seam as continuous as any other point
    head = _add(bytes(data[:tail * 2]), bytes(data[total * 2:(total + tail) * 2]))
    pcm = head + bytes(data[tail * 2:total * 2])
    return _normalize(pcm)


def _normalize(pcm):
    if audioop is not None:
        peak = audioop.max(pcm, 2)
    else:
        import array
        arr = array.array("h")
        arr.frombytes(pcm)
        peak = max(abs(v) for v in arr)
    if peak <= 0:
        return pcm
    return _mul(pcm, min(3.0, 0.85 * 32767 / peak))


def _power(root_midi, dur, vol, detune=1.004):
    f = _freq(root_midi)
    a = _tone(f, dur, vol, "square", release=0.02)
    b = _tone(f * 1.5 * detune, dur, vol * 0.8, "square", release=0.02)
    return _add(a, b[:len(a)] + b"\x00" * max(0, len(a) - len(b)))


def _rhythm_bar(buf, at, s0, style, sec, root, step_s, loud):
    v = 0.11 * loud
    if style in ("rock", "punk", "gallop"):
        if sec == "chorus" or sec == "bridge":
            hits = [(0, 8), (8, 8)] if style != "punk" else [(i, 2) for i in range(0, 16, 2)]
        elif style == "gallop":
            hits = [(i, 1) for g in range(0, 16, 4) for i in (g, g + 2, g + 3)]
        else:
            hits = [(i, 2) for i in range(0, 16, 2)]
        for st, n in hits:
            d = n * step_s * (0.55 if n <= 2 else 0.95)
            buf.add(at(s0 + st), _power(root, d, v * (1.1 if st % 4 == 0 else 0.85)))
    elif style == "shuffle":
        for st in (0, 3, 4, 7, 8, 11, 12, 15):
            long_ = st % 4 == 0
            buf.add(at(s0 + st), _power(root, step_s * (2.4 if long_ else 0.9), v * (1.0 if long_ else 0.7)))
    elif style == "ballad":
        arp = (0, 7, 12, 7, 16 if sec == "chorus" else 15, 7, 12, 7)
        for i, iv in enumerate(arp):
            buf.add(at(s0 + i * 2), _tone(_freq(root + iv), step_s * 3.5, 0.075 * loud, "pulse", release=0.08))
    elif style in ("halftime", "doom"):
        buf.add(at(s0), _power(root, 16 * step_s * 0.97, v * 1.05, detune=1.008 if style == "doom" else 1.004))
        if style == "halftime" and sec == "chorus":
            buf.add(at(s0 + 10), _power(root, 6 * step_s * 0.9, v * 0.8))
    elif style == "tribal":
        for st, n in ((0, 3), (6, 2), (10, 3), (14, 2)):
            buf.add(at(s0 + st), _power(root, n * step_s * 0.7, v))
    elif style == "surf":
        for st in range(0, 16):     # tremolo-picked 16ths
            buf.add(at(s0 + st), _power(root, step_s * 0.6, v * (0.9 if st % 4 == 0 else 0.6)))
    elif style == "offbeat":
        for st in (2, 6, 10, 14):   # chords on the "and"
            buf.add(at(s0 + st), _power(root, step_s * 1.4, v * 0.95))


def _bass_bar(buf, at, s0, style, root, spec, deg, step_s, loud):
    v = 0.16 * loud
    tri = lambda midi, n, vol=v: _tone(_freq(midi), n * step_s * 0.9, vol, "triangle", release=0.02)
    if style in ("rock", "punk", "gallop", "surf"):
        for st in range(0, 16, 2):
            buf.add(at(s0 + st), tri(root + (7 if style == "rock" and st in (6, 14) else 0), 2))
    elif style == "shuffle":
        sc = SCALES[spec["scale"]]
        walk = [0, 4 if 4 in sc else 3, 7, 9 if 9 in sc else 10]
        for i, st in enumerate((0, 4, 8, 12)):
            buf.add(at(s0 + st), tri(root + walk[i], 4))
    elif style in ("halftime", "doom"):
        buf.add(at(s0), tri(root, 8))
        buf.add(at(s0 + 8), tri(root + (0 if style == "doom" else 7), 8))
    elif style == "ballad":
        for st in (0, 4, 8, 12):
            buf.add(at(s0 + st), tri(root + (7 if st == 8 else 0), 4, v * 0.8))
    elif style == "tribal":
        for st in (0, 3, 6, 10, 12):
            buf.add(at(s0 + st), tri(root, 2))
    elif style == "offbeat":
        for st, iv in ((0, 0), (3, 0), (6, 7), (8, 12), (12, 7)):
            buf.add(at(s0 + st), tri(root + iv, 2))


_DRUM_PATTERNS = {
    #            kick steps                 snare steps         hat steps
    "rock": ((0, 6, 8), (4, 12), range(0, 16, 2)),
    "punk": ((0, 4, 8, 12), (4, 12), range(0, 16, 2)),
    "gallop": ((0, 2, 3, 4, 6, 7, 8, 10, 11, 12, 14, 15), (4, 12), range(0, 16, 4)),
    "shuffle": ((0, 8), (4, 12), (0, 3, 4, 7, 8, 11, 12, 15)),
    "ballad": ((0, 10), (8,), range(0, 16, 4)),
    "halftime": ((0, 10), (8,), range(0, 16, 2)),
    "doom": ((0,), (8,), range(0, 16, 8)),
    "tribal": ((0, 7, 10), (), range(0, 16, 4)),
    "surf": ((0, 8), (4, 12), range(0, 16, 1)),
    "offbeat": ((0, 8), (8,), (2, 6, 10, 14)),
}


def _drum_bar(buf, at, s0, style, sec, b, nbars, loud):
    kicks, snares, hats = _DRUM_PATTERNS[style]
    if sec == "intro" and b < 2:
        hats = range(0, 16, 4)
        snares = ()
    if sec == "bridge":
        kicks = kicks[:1]
    g = loud
    for st in kicks:
        buf.add(at(s0 + st), _mul(_drum("kick"), g))
    for st in hats:
        buf.add(at(s0 + st), _mul(_drum("hat"), g * (1.0 if st % 4 == 0 else 0.7)))
    fill = b == nbars - 1 and sec != "intro"
    for st in snares:
        if fill and st >= 8:
            continue
        buf.add(at(s0 + st), _mul(_drum("snare"), g))
    if style == "tribal":
        for st, t in ((2, "tom_hi"), (5, "tom_hi"), (12, "tom_lo"), (14, "tom_lo")):
            buf.add(at(s0 + st), _mul(_drum(t), g))
    if fill:   # a short snare/tom fill that leads into the next section (or back to the loop start)
        for st in range(8, 16, 2 if style in ("doom", "ballad", "halftime") else 1):
            buf.add(at(s0 + st), _mul(_drum("snare" if st < 12 else "tom_lo"), g * (0.55 + st / 40)))
    if b == 0 and sec == "chorus":
        buf.add(at(s0), _mul(_drum("crash"), g))


# ----------------------------------------------------------------- cache

_SRC_HASH = None


def _src_hash():
    global _SRC_HASH
    if _SRC_HASH is None:
        try:
            with open(__file__, "rb") as f:
                _SRC_HASH = hashlib.md5(f.read()).hexdigest()[:10]
        except OSError:
            _SRC_HASH = "nosrc"
    return _SRC_HASH


def cache_dir():
    d = os.environ.get("RR_MUSIC_CACHE")
    if not d:
        from game import settings
        d = os.path.join(os.path.dirname(os.path.abspath(settings.SETTINGS_PATH)), "music_cache")
    return d


def cache_path(zone, rate=RATE):
    spec = TRACKS[zone]
    h = hashlib.md5((_src_hash() + repr(sorted(spec.items())) + str(rate)).encode()).hexdigest()[:12]
    return os.path.join(cache_dir(), f"{zone}_{h}_{rate}.wav")


def wav_bytes(pcm, rate=RATE):
    bio = io.BytesIO()
    with wave.open(bio, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(pcm)
    return bio.getvalue()


def load_or_render(zone, rate=RATE):
    """WAV bytes for `zone`, from the disk cache or freshly rendered (and cached)."""
    path = cache_path(zone, rate)
    try:
        with open(path, "rb") as f:
            return f.read()
    except OSError:
        pass
    data = wav_bytes(compose_and_render(TRACKS[zone], rate), rate)
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "wb") as f:
            f.write(data)
        os.replace(tmp, path)
    except OSError:
        pass  # read-only install - just re-render next launch
    return data


# ------------------------------------------------------ background worker

class Library:
    """Thread-safe front for the game loop: request(zone) returns WAV bytes if the
    track is ready, otherwise schedules it (front of the queue) and returns None
    immediately. A single daemon worker then pre-renders every other track in the
    background so later zone changes are instant."""

    def __init__(self, rate=RATE, prewarm=True):
        self.rate = rate
        self._ready = {}
        self._queue = []
        self._lock = threading.Lock()
        self._wake = threading.Event()
        self._thread = None
        self._prewarm = prewarm

    def request(self, zone):
        if zone not in TRACKS:
            return None
        with self._lock:
            data = self._ready.get(zone)
            if data is not None:
                return data
            if zone in self._queue:
                self._queue.remove(zone)
            self._queue.insert(0, zone)
            if self._prewarm and len(self._queue) == 1 and not self._ready:
                self._queue += [z for z in TRACKS if z != zone]
        self._ensure_thread()
        self._wake.set()
        return None

    def is_ready(self, zone):
        with self._lock:
            return zone in self._ready

    def _ensure_thread(self):
        if self._thread is None or not self._thread.is_alive():
            self._thread = threading.Thread(target=self._run, name="music-render", daemon=True)
            self._thread.start()

    def _run(self):
        while True:
            with self._lock:
                zone = next((z for z in self._queue if z not in self._ready), None)
                if zone is not None:
                    self._queue.remove(zone)
            if zone is None:
                self._wake.wait(1.0)
                self._wake.clear()
                continue
            try:
                data = load_or_render(zone, self.rate)
            except Exception:  # music must never crash the game
                data = None
            if data is not None:
                with self._lock:
                    self._ready[zone] = data


class Hysteresis:
    """Stable choice from a jittery candidate (e.g. the biome under the player):
    the value only changes after the new candidate has held for `dwell` seconds,
    so walking along a border doesn't flip-flop between two things."""

    def __init__(self, dwell=2.0):
        self.dwell = dwell
        self.value = None
        self._cand = None
        self._t = 0.0

    def update(self, dt, candidate):
        if self.value is None:
            self.value = candidate
            return self.value
        if candidate == self.value:
            self._cand, self._t = None, 0.0
            return self.value
        if candidate != self._cand:
            self._cand, self._t = candidate, 0.0
        self._t += dt
        if self._t >= self.dwell:
            self.value, self._cand, self._t = candidate, None, 0.0
        return self.value

    def reset(self, value=None):
        self.value, self._cand, self._t = value, None, 0.0
